version: '3.4'

services:
  jsfprimeface:
    image: notdyy2544/jsfprimesface
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./DEBUG/tomcat/logs:/usr/local/tomcat/logs
