name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: notdyy2544/jsfprimeface:latest
          
  deploy_to_aws_ec2:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull notdyy2544/jsfprimeface:latest
            docker stop jsfprimeface || true
            docker rm jsfprimeface || true
            docker run -d --name your-container-name -p 80:8080 notdyy2544/jsfprimeface:latest